// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb2C_epcZPfHAmVUx964_-hwalX_aprPg',
    appId: '1:372140469373:web:f8f45bd03b38257bf1d514',
    messagingSenderId: '372140469373',
    projectId: 'paratha-online',
    authDomain: 'paratha-online.firebaseapp.com',
    storageBucket: 'paratha-online.appspot.com',
    measurementId: 'G-Y94KYBNJ8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjuSdjGi8hZOMoZzsQuZvn4jpWb1f6HGQ',
    appId: '1:372140469373:android:5652f2b1e1302749f1d514',
    messagingSenderId: '372140469373',
    projectId: 'paratha-online',
    storageBucket: 'paratha-online.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRaoQWniQexGw_2sQoLv60_uHIt27Dr9A',
    appId: '1:372140469373:ios:4d7e5ad4cf3efe15f1d514',
    messagingSenderId: '372140469373',
    projectId: 'paratha-online',
    storageBucket: 'paratha-online.appspot.com',
    iosBundleId: 'com.example.parathaOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRaoQWniQexGw_2sQoLv60_uHIt27Dr9A',
    appId: '1:372140469373:ios:262f548bedc5fe08f1d514',
    messagingSenderId: '372140469373',
    projectId: 'paratha-online',
    storageBucket: 'paratha-online.appspot.com',
    iosBundleId: 'com.example.parathaOnline.RunnerTests',
  );
}
